### ISSUE TITLE
When will Helm charts for CF/Diego be officially released?

### ISSUE THREAD

**Issue by mattcui** [SUSE/scf#1023]
Sorry that I am just asking a question here, since I didn't find a better place to ask questions, like Slack. I am just wondering when Helm charts for CF/Diego will be officially released (GAed), we expect to do some experimental or pilot with these charts as early as possible. And will it support Ubuntu OS? Thanks.

**Comment by troytop** [comment]
We haven't announced any release dates yet. If you keep an eye on this repo, you'll soon see some deployable charts that you can experiment with.

The container images referenced in the charts will be based on openSUSE. The system will include the Ubuntu-based cflinuxfs2 stack along with a compatible openSUSE stack, but the core CF components will be running in openSUSE containers.

If you're interested in this work, feel free to join us on the #fissile channel in the [CF](slackhttps://cloudfoundry.slack.com/).

**Comment by aarondl** [comment]
There are deployable helm charts in the releases section now.
