### ISSUE TITLE
Cannot generate smoke and CATs Test by using helm?

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1185]
Hi,

I would like to add smoke test in my building.

But I found I need to generate Kubernetes configuration first. and use `make smoke` or `make make cats` to run the tests. 

But SCF prefer to use *helm* deploy, and I have to re-generate kube config for tests...

Not sure if SCF can generate smoke/cats test like post-deployment-setup. then I can use it directly.

**Comment by aarondl** [comment]
We've discussed this in the past but felt that it wasn't necessary to create helm charts for these short-running processes. Helm's model doesn't really fit that, the best you could describe them as is hooks, but even then it's pretty odd.

All `make smoke/cats/brain` do is run a kubernetes job with some environment variables, this is something fairly easily doable from kubernetes itself. When you do a `make helm` or `make kube` we output Kubernetes yamls for the test jobs that you can use to make things work.

**Comment by zhangtbj** [comment]
Got it. Thanks @aarondl
