### ISSUE TITLE
Consul cluster member cannot started normally

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1228]
Sorry @viovanov ,

We need an issue to track our problem. So I open this consul issue for tracking. Thanks! :)

I have a question about Consul, I am not sure if you can start the HA Consul clusters, such as 3 members?
Such as I set 3 consuls in SCF, then SCF will render consul confab.json as:
```
"servers":{"lan":["consul-0.consul-set.cf.svc.cluster.local","consul-1.consul-set.cf.svc.cluster.local","consul-2.consul-set.cf.svc.cluster.local"]
```
The consul-0 can start correctly, but for consul-1 and consul-2, they cannot start correctly because they need to communicate each other successfully, so for service of consul, if pod is not ready, we cannot access its pod by using the pod of service name, I think it is a dead lock.....
for example, I see the error in consul-1 consul_agent.stderr.log:
```
* Failed to resolve consul-2.consul-set.cf.svc.cluster.local: lookup consul-2.consul-set.cf.svc.cluster.local on 172.21.0.10:53: no such host)
```
So consul-1 cannot startup correctly, then consul-set service cannot discover it

But later, I am not sure why consul-2 is provisioned and started, then search consul-1 then get the same error. 

So these two wait each other to startup but none of them is ready then dead lock here....

But several hours later, for some reason, they may know each other correctly, then they can start up correctly. But I don't know why or how they do that.

**Comment by jandubois** [comment]
This issue seems obsolete; there is no consul release in SCF anymore.
