### ISSUE TITLE
Latest fissile doesn't support --use-secrets-generator for build kube

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1229]
Hi @mook-as ,

I see you upgrade fissile to support --use-secrets-generator.

But when I use the official fissile-5.1.0+20.g253c0ab from fissile master. I see only `fissile build helm` supports parameter --use-secrets-generator, but `fissile build kube` doesn't support.
Then when `make vagrant-prep`, it will call `make images` but `make images` will finally call `make helm` and `make kube`:
`images: bosh-images uaa-images helm kube`

Then the build process will fail at make kube because:
make/uaa-kube
make[1]: Entering directory `/bcf-maker/bcf/src/scf/src/uaa-fissile-release'
make/kube
unknown flag: --use-secrets-generator
make[1]: *** [kube] Error 1
make[1]: Leaving directory `/bcf-maker/bcf/src/scf/src/uaa-fissile-release'
make: *** [uaa-kube] Error 2

When I execute `fissile build kube --help`:
```
Flags:
  -D, --defaults-file string   Env files that contain defaults for the parameters generated by kube
      --output-dir string      Kubernetes configuration files will be written to this directory (default ".")
      --tag-extra string       Additional information to use in computing the image tags
      --use-memory-limits      Include memory limits when generating kube configurations (default true)
```
I also didn't find parameter --use-secrets-generator.

Can you help check, thanks!

**Comment by zhangtbj** [comment]
I found this issue has been fixed in:
https://github.com/SUSE/scf/commit/cc19485b9c2b27545c72bd8a84d650f42203231a

Thanks!

**Comment by mook-as** [comment]
I was on vacation, but it sounds like the actual issue has been resolved at this point? Closing, please ping back if that's not the case and I'll happily reopen this 😄
