### ISSUE TITLE
Release notes are missing the current cf-deployment version used

### ISSUE THREAD

**Issue by qu1queee** [SUSE/scf#1364]
Quick question, does the release notes, have any information of the current `cf-deployment` version used in that SCF release? If not, can we add this?

Thanks.

Enrique Encalada
IBM

**Comment by jonsger** [comment]
I think we use cf-deployment version 1.9.0 as written in the [release notes](https://github.com/SUSE/scf/releases/tag/2.7.0). The related upstream release notes can be found [here](https://github.com/cloudfoundry/cf-deployment/releases/tag/v1.9.0).

**Comment by qu1queee** [comment]
Hi,

yes [2.7.0](https://github.com/SUSE/scf/releases/tag/2.7.0) its quite clear, but in [1.9.1](https://github.com/SUSE/scf/releases/tag/1.9.1) , was not. I know from the logs that at 1.9.1, the cf-deployment version still 1.9.0, but I was expecting to see this explicit in that release notes. Saves some time, when trying to figure it out.

Regards,
Enrique Encalada

**Comment by qu1queee** [comment]
@jonsger yes, we maintain different environments with different versions(e.g. 1.9.1), we cannot bump so easily to the latest on your side. I think we can close this issue, I was just asking if it will be possible to be very explicit with the `cf-deployment` valid version in each release SCF is releasing. e.g. one spot (either release notes, or a file) where we can always find that reference.

**Comment by cornelius** [comment]
The name of the release assets contains the cf-deployment version (for example, the `cf1.9.0` part in `https://github.com/SUSE/scf/releases/download/2.7.0/scf-opensuse-2.7.0.cf1.9.0.0.g2d95fcb5.darwin-amd64.zip` from https://github.com/SUSE/scf/releases/tag/2.7.0). That should be the reference. We will also make sure that the release notes contain the version bumps.
