### ISSUE TITLE
`helm list`error maximum size exceeded

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1367]
I see SCF uses `helm list` to get/remove some releases.

But there is a limitation in the latest helm 2.8.1:

If you have many helm releases, for example more than 100 releases, when you just use `helm list` you will get an error:
root@0013473c434b:/# helm list
Error: grpc: received message larger than max (9677174 vs. 4194304)

Then it will fail the build process and get nothing.

I have talked with helm team but no fix right now, there is an issue:
https://github.com/kubernetes/helm/issues/3322

For example your code will fail at:
```
# Determine the kube revision of the chart controlling the specified namespace.
release_version() { helm list --namespace "$1" | awk '{ print $2 }' | tail -n 1 ; }
```

I use some additional parameters to limit the list size like this:
```
release_version() { helm list -d -r --max 20 --namespace "$1" | awk '{ print $2 }' | head -n 1 ; }
```

We can get the latest one by using -d -r and with max size.

Let me know if you need a PR for it.

Thanks!

**Comment by mook-as** [comment]
Hi!

Thanks for the report; it sounds like a good thing to change.  We'll probably get to it at some point, but if it's causing you issues, feel free to make a PR too.

**Comment by zhangtbj** [comment]
Sure thing. I will confirm with helm team in https://github.com/kubernetes/helm/issues/3322, if they plan fix it soon, I will tell us the new version. If not, I will provide the fix later.

**Comment by zhangtbj** [comment]
Hi @mook-as ,

I have confirmed with helm team, they still fixed by hardcode output size from 4MB to 20MB.

They didn't solve the root problem, but a reasonable fix.

We are using a development environment which have many helm releases, in future, it may still report the error again.

But for the normal user, it should be hard to reach 20MB size when using `helm list`

If you still agree, I can raise a PR to use `helm list -d -r --max 1` to limit the output list size in all run/stop/upgrade, ...

Or you think the 20MB is enough in current stage?

**Comment by mook-as** [comment]
I think doing the `helm list` change is still reasonable; but then, I was also thinking of (separately) having fixed release names (for the various development scripts) so it wouldn't pile up like this.

I'll be happy to take either change (or both, in 2 PRs, if you feel like it). I'm just too busy trying to run guardian tests right now :D

**Comment by zhangtbj** [comment]
Sure thing @mook-as ,
I have created two PRs for both CF and UAA:
https://github.com/SUSE/scf/pull/1376
https://github.com/SUSE/uaa-fissile-release/pull/81
for the `helm list` limitation issue. Pls review

About the *(separately) having fixed release names*, do you mean config special release name instead of random name?
We changed them in our deployment, like this:
```
✔ $ helm list -d -r --max 2 
NAME                    REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
cf.20180302.061007      1               Fri Mar  2 14:09:49 2018        DEPLOYED        cf-270.21.0-2950146     cf       
uaa.20180302.060236     1               Fri Mar  2 14:02:17 2018        DEPLOYED        uaa-270.21.0-2950146    uaa      
```

If yes, we can do it separately, Thanks!

**Comment by bacongobbler** [comment]
fixes are present in master now as of https://github.com/kubernetes/helm/pull/3514. You can Try the canary release of Helm and it should work again.

**Comment by zhangtbj** [comment]
@mook-as ,

New helm version 2.8.2 is published,

You can use the new one:
https://github.com/kubernetes/helm/releases/tag/v2.8.2
