### ISSUE TITLE
Routing submodule should be udpated

### ISSUE THREAD

**Issue by qu1queee** [SUSE/scf#1371]
Hi,

Quick question regarding the `routing-release`submodule. It seems that in the current scf latest release its using cf-deployment 1.9, then the correct `routing-release` version  should be something higher than [0.166.0](https://github.com/cloudfoundry/routing-release/tree/cf51f58c937450c37996f8560621f25a68eb59e9), apparently `0.170.0`. Any ideas on this?

Regards,
Enrique Encalada

**Comment by alexjh** [comment]
It looks like this was an oversight, but it will be updated when https://github.com/SUSE/scf/pull/1366 is merged.
