### ISSUE TITLE
hardcode mysql-0 in make/run is not good for common usage

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1416]
I see SCF update the secret name and modify the way to get it in `make/run`

```
get_uaa_secret_name() {
    kubectl get pod mysql-0 --namespace "${UAA_NAMESPACE}" \
            -o jsonpath='{@.spec.containers[0].env[?(@.name=="MONIT_PASSWORD")].valueFrom.secretKeyRef.name}'
}
```

But it hardcode mysql-0 in `make/run`, and we are not using mysql in our env, so it will fail here.

I think SCF can change it more common, such as get the first pod name as:
```
pod_name=`kubectl get pod --namespace "${UAA_NAMESPACE}" | grep "\-0" | awk '{ print $1 }' | head -1`
```

Then you don't need hardcode a pod name here.

Pls let me know if it is better, I can provide a PR if need.

**Comment by andreas-kupries** [comment]
Looking at https://github.com/SUSE/scf/blob/develop/make/include/secrets we seems to have made changes similar to what is requested. Difference mainly in using a `jsonpath` directive to perform filtering and extraction instead of grep.

Outdated, closing.
