### ISSUE TITLE
ccdb migration in statefulset api upgrade

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1455]
Hi,

Right now, we are testing upgrade function in SCF. But api is a special case because it needs to do the ccdb migration in the beginning.

But api is statefulset, during upgrade, it will upgrade reversely. it mean, api-1 will be upgraded, then api-0 is upgraded then do ccdb migration. I think it is incorrect.

I check the api code:
```
 <% if spec.bootstrap && p('cc.run_prestart_migrations') %>
  perform_migration
  seed_db
  <% else %>
  echo "Skipping DB migrations and seeds"
  <% end %>
```
every time, api-0 will do perform_migration and seed_db.

I also asked in kubernetes git, there is no any option to upgrade in order for statefulset right now:
https://github.com/kubernetes/kubernetes/issues/51907#event-1572703466

So I am not sure if we can upgrade like this:
1, set statefulset api upgradestrategy as `OnDelete`
make a scripts for api upgrade, after make upgrade, use script to delete api-0 -> api-1 -> etc... in order.

Or do you have any plan for that?

Thanks a lot!

**Comment by alexjh** [comment]
This was fixed by a commit yesterday:
https://github.com/SUSE/scf/commit/b7a1ee069922d75d23b5057dcf45d5b0255a4237

The actual code change is here:
https://github.com/SUSE/configgin/commit/6f129a9ed5106bf1fc671da9280161236c919187
