### ISSUE TITLE
"disk quota exceeded" on overlay2 and ubuntu

### ISSUE THREAD

**Issue by adrianliechti** [SUSE/scf#1460]
hi scf team,

we successfully deployed scf 2.7.0 on a kubespray kubernetes cluster.
as host/node os, we currently use ubuntu on aws with overlay2 as docker storage driver.

while deploying apps, we noticed "Disk quota exceeded" and likewise exceptions all over
(like from npm and other package managers).

we increased the maximal disk space of apps from 2GB to 10 GB
(using MAX_APP_DISK_IN_MB helm value -> cc.maximum_app_disk_in_mb)
if we now push the app while specifying the disk size with e.g. -k 10G it magically works.
the disk usage calculation with "cf app {app-name}" seems correct ~ 100 MB

we assume, the quota calculation on the diego-cell (fissile?) wrongly sums up both, the app's stack size (opensuse / cflinux2) and the app size, and is therefore more or less always over its quota.

let me know if I can provide any information to help fixing that issue

best regards, adrian

**Comment by zhangtbj** [comment]
hi, We also met this problem when using scf on Ubuntu.

You have to change the garden rootfs drive in Role-manifest.yaml to overlay to:
GARDEN_ROOTFS_DRIVER: "overlay-xfs"

Then the problem should be solved.

**Comment by adrianliechti** [comment]
@zhangtbj thank you super much!!
we will try this asap. awesome!!

**Comment by adrianliechti** [comment]
it works! it really works! you made our day @zhangtbj
cheers!
