### ISSUE TITLE
Statefulset nodes fail to start on Kubernetes 1.9

### ISSUE THREAD

**Issue by HeavyWombat** [SUSE/scf#1492]
Hey there, @qu1queee and I investigated an issue colleagues of us had with a version of SCF we have deployed. In that cluster,  `nats` is a statefulset with two nodes. The first one came up just fine, the second one failed to start with some weird error messages.

We debugged it so far that we think that [configure-HA-hosts.sh](https://github.com/SUSE/scf/blob/2.8.0/container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh#L44) relies on a certain structure of Kubernetes API result JSON that changes between version 1.8 and 1.9 of Kubernetes.

In 1.8, the JSON result has `kubernetes.io/created-by`:
```json
{
  "checksum/config": "[...]",
  "kubernetes.io/created-by": "{[...],\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"StatefulSet\",\"name\":\"nats\", [...]}"
}
```

From what we can see, our 1.9 Kubernetes cluster API result does not have anything like that. There seems to be a new section with details about the name that could be used.

We wanted to check with you if you encountered a similar issue, too? Thanks in advance for your feedback.

@zhangtbj @zhanggbj @ScarletTanager FYI

**Comment by Flask** [comment]
@HeavyWombat That feature was deprecated in Kubernetes 1.8 and removed in 1.9.

You still can edit the statefulset for mysql and nats manually to add the annotation `kubernetes.io/created-by: '{"reference":{"name":"mysql"}}'` (nats for the other statefulset. 

Another issue we ran into was the configgin-role for scf, where the "list" verb was missing.

Besides those two things it seems to run quite nice on 1.9.6

Cheers

**Comment by Xiaohua-Shen** [comment]
another way to fix this is using `.metadata.ownerReferences[0].name`, which have same output for 1.8 and 1.9.  

```
# kubectl get pod nats-0 -n cf -o json | jq .metadata.ownerReferences[0].name
"nats"
# kubectl get pod nats-1 -n cf -o json | jq .metadata.ownerReferences
[
  {
    "apiVersion": "apps/v1beta1",
    "blockOwnerDeletion": true,
    "controller": true,
    "kind": "StatefulSet",
    "name": "nats",
    "uid": "6b779637-495f-11e8-8381-16336b7583f8"
  }
]
```

**Comment by alexjh** [comment]
@HeavyWombat @Xiaohua-Shen ,

We've added a Kube 1.9 upgrade to our sprint so we can test pr #1494. We should have an update for you soon.

**Comment by HeavyWombat** [comment]
You guys are awesome. Thanks for looking into this.

**Comment by mook-as** [comment]
Merged in https://github.com/SUSE/scf/commit/e92a03ebf4eedd75dd08491243c4d048200f4102; thanks for the patch (and reminding me that this wasn't merged yet)!
