### ISSUE TITLE
error when value of a bosh release property is a mapping

### ISSUE THREAD

**Issue by qibobo** [SUSE/scf#1588]
I have a bosh release and in it there is a property: broker.catalog, the value of it is a mapping. When I build my bosh release it threw an error that no bosh release use "broker.catalog.services". The "services" is just a sub-elements of catalog while catalog is used by my bosh release. Is it a bug of scf?
  catalog: 
          services:
          - id: autoscaler-guid
            name: autoscaler
            description: Automatically increase or decrease the number of application instances based on a policy you define.
            bindable: true
            plans:
            - id: autoscaler-free-plan-id
              name: autoscaler-free-plan
              description: This is the free service plan for the Auto-Scaling service.

**Comment by jandubois** [comment]
We have implemented support for structured properties (arbitrary slices and mappings) in fissile in https://github.com/SUSE/fissile/pull/363

You can see how it can be used in SCF in the comments in that PR.

It has been applied to SCF in https://github.com/SUSE/scf/pull/1613, which has now been merged into `develop`.

Please re-open if this doesn't give you all the functionality you need for your release.
