### ISSUE TITLE
diego-release submodule nats is out of date which make build process fail

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1592]
Hi, after talked with @viovanov ,

Recently there is a change that cf change nats name from nats to go-nats, and the repo ulr is also changed:
https://github.com/cloudfoundry/diego-release/tree/20c48cc98c7b78aff2c65a5c3df2b5ff612e2d61/src/github.com/nats-io

The original nats one is missed:
https://github.com/nats-io/nats/tree/c0ad3f079763c06c3ce94ad12fa3f17e78966d99

manual workaround:
`git submodule sync --recursive ;  git submodule update --init`
and change .gitmodule:
```
[submodule "src/github.com/nats-io/nats"]
        path = src/github.com/nats-io/nats
        url = https://github.com/nats-io/go-nats
        branch = master
```
by `perl -pi -e "s/https:\/\/github.com\/nats-io\/nats/https:\/\/github.com\/nats-io\/go-nats/g" .gitmodules`

Open this issue and wait for official fix from SCF team.

**Comment by jandubois** [comment]
For now we have bumped `diego-release` to point to the commit that updates the nats submodule to point to go-nats instead: https://github.com/SUSE/scf/pull/1593

We'll bump it again once there is a proper release of diego-release that contains this change.
