### ISSUE TITLE
Failing readiness check for diego-access

### ISSUE THREAD

**Issue by qu1queee** [SUSE/scf#1655]
Hello,

For weird reasons, we wanted to bump the `diego-release` in SCF a couple of versions and ran into an issue with the readiness check done by the `diego-access` pod. In a future SCF version, you could have the same issue, too.

So it is not of immediate concern, but we thought we share our observations already. The `file-server` package was [bumped to a newer version](https://github.com/cloudfoundry/diego-release/commit/0858ad43bd0215fac73933f7064ef8379cb48d63). This comes with [an API change](https://github.com/cloudfoundry/fileserver/commit/18b7a7757e5f9faff45aed525feab2fc0f34f80f#diff-c7b59f7230a7c355f4a850d2f54cd938R150), which manifests itself by returning a `401` when requesting a directory. Since the readiness check requests `/v1/static/` (`/v1/static` will be 302-redirected to `/v1/static/`), which is a directory, an offending `401` is returned. This causes Kubernetes to mark the container of that pod unhealthy.

We are currently testing an alternative, and it seems the readiness check should evaluate an specific file, rather than a directory. Or, a completely different readiness check should be used.

**Comment by prabalsharma** [comment]
Hello,
Thanks for bringing this to our attention. 

@viovanov please take a note of this. I will create a ticket.

**Comment by jandubois** [comment]
This has been addresses in the bump to cf-deployment-2.7: https://github.com/SUSE/scf/commit/60f28def294d484fc3a700aca7ccdba573185a51
