### ISSUE TITLE
Remove consul from SCF

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1672]
Hi,

I remember SCF brings Consul back for the new auto-scaling feature.

I have confirmed with auto-scaling that they don't need consul any more and remove consul related config in auto-scaling.

Can you help remove consul job if there is no any other jobs need Consul?

@qibobo here, if you have any auto-scaling question.

Thanks!

**Comment by gaktive** [comment]
We have a backlog task to remove consul from SCF as we only added it based on an earlier implementation of the App Autoscaler and no other service requires it.

I'll let you know once that work is in progress, then done.

Thanks!

**Comment by jandubois** [comment]
#1779 has removed the unused consul and postgres roles.
