### ISSUE TITLE
secret name is gathered incorrectly

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/scf#1780]
demo:~ # SECRET=$(kubectl get pods --namespace uaa -o jsonpath='{.items[*].spec.containers[?(.name=="uaa")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretK
eyRef.name}')
demo:~ # echo $SECRET
secrets-2.13.3-1 secrets-2.13.3-1     <<----- HERE 
demo:~ # CA_CERT="$(kubectl get secret $SECRET --namespace uaa -o jsonpath="{.data['internal-ca-cert']}" | base64 --decode -)"
demo:~ # echo $CA_CERT

demo:~ #
```
 
 ```
demo:~ # SECRET=secrets-2.13.3-1
demo:~ # kubectl get secret $SECRET --namespace uaa -o jsonpath="{.data['internal-ca-cert']}"
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4akNDQXRxZ0F3SUJBZ0lVUFhKczRlbzFERnpjY1NtcFRPeVd3QT

**Comment by abonillasuse** [comment]
This is when on HA mode - adding  "| head -1" doesn't do it because it's on separate lines

**Comment by mook-as** [comment]
https://github.com/SUSE/doc-cap/issues/171 was updated in the docs; the wiki was fixed in https://github.com/SUSE/scf/wiki/How-to-Install-SCF/_compare/cedfa17f64f422b1b1d410fa1ef80c50612e0292...3dab44843a3a1a271dd26fca7d15646358a93878 — closing
