### ISSUE TITLE
Allow well-known IPs to be used by key load balancers

### ISSUE THREAD

**Issue by DanielJonesEB** [SUSE/scf#1781]
We have a use case whereby we provision static IPs on our IaaS and configure DNS to point to these, _before_ deploying SCF. This allows users to install UAA and SCF one after the other without stopping to reconfigure DNS with whichever LoadBalancer IP the IaaS happened to choose.

Suggest that three properties are added to the respective Helm charts:

```
services.uaa_load_balancer_ip
services.router_load_balancer_ip
services.ssh_load_balancer_ip
```

And then the Helm charts (or whatever bit of Fissile generates them) are changed to contain the following logic:

```
    {{- if .Values.services.loadbalanced }}
    type: "LoadBalancer"
    {{ if .Values.services.router_load_balancer_ip }}loadBalancerIP: {{ .Values.services.router_load_balancer_ip }} {{ end }}
    {{- end }}
```

**Comment by f0rmiga** [comment]
This issue is pretty old. I'll close due to inactivity. Please, reopen if it's somehow still relevant.
