### ISSUE TITLE
[Istio Integration] Support Istio automatic sidecar injection

### ISSUE THREAD

**Issue by zhanggbj** [SUSE/scf#1960]
To support Istio automatic sidecar injection, the Kubernetest cluster api server should meet the requirements as below(https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection):

Verify that the `kube-apiserver` process has the` admission-control` flag set with the MutatingAdmissionWebhook and ValidatingAdmissionWebhook admission controllers added and listed in the correct order and the admissionregistration API is enabled.

```
$ kubectl api-versions | grep admissionregistration
admissionregistration.k8s.io/v1alpha1
admissionregistration.k8s.io/v1beta1
```

In **scf Vagrant VM**, this is not fully **enabled**. So need to enable it in Vagrant VM.
```
$ kubectl api-versions | grep admissionregistration
admissionregistration.k8s.io/v1beta1
```

**Comment by mook-as** [comment]
It'll probably need to change around https://github.com/SUSE/scf/blob/fec8cd4284c9cbc43bb0775519b2dd9599e6aded/packer/http/apiserver-vagrant-overrides.env ?

**Comment by zhanggbj** [comment]
Hi @mook-as,

Thanks for the info. Yes, I think we may need to add `--enable-admission-plugins PodSecurityPolicy,MutatingAdmissionWebhook,ValidatingAdmissionWebhook`. 

I would like to build a new vagrant box and verify it, is this the right way? How to get these account? Sorry if the question is silly, I have not much experience about Vagrant.
```
make vagrant-box
make/vagrant-box
aws-slave output will be in this color.
jenkins-slave output will be in this color.
scf-cached-libvirt output will be in this color.
vagrant-libvirt output will be in this color.
vagrant-virtualbox output will be in this color.
vagrant-vmware output will be in this color.

4 error(s) occurred:

* triton_account is required to use the triton builder
* triton_key_id is required to use the triton builder
* Error creating Triton request signer: environment variable SSH_AUTH_SOCK not set
* A source_machine_package must be specified
```

**Comment by mook-as** [comment]
Hi!

Ignore the Triton stuff, just do `make -C packer  vagrant-virtualbox vagrant-libvirt`.  We should get rid of the obsolete targets… (I didn't realize that existed)

That will get you the `.box` files, which you can locally `vagrant add` (using the matching URL as the desired name) for testing. We'll need to push to the S3 buckets, though.

**Comment by mook-as** [comment]
Ah, also, it looks like @bikramnehra might be trying to do this right now; might want to figure out which one is doing the work :)
