### ISSUE TITLE
uaa redeployment results in missconfigured certificates ( Related to #1877 )

### ISSUE THREAD

**Issue by christiancloudibility** [SUSE/scf#2023]
As secrets are not cleaned up correctly with "helm delete --purge" Redeployment of uaa and mysql uses the existing secret, just before a new one is created via secret-generation-pod.

That results in a failing deployment, as scf-containers will be created with the correct secret anyway which causes a wrong ca-certificate

**Comment by jandubois** [comment]
Thank you for your report!

This is a known issue; the workaround is to delete the namespace after deleting the helm deployment: https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.rebuild.depl

This will be fixed when SCF will be deployed via the cf-operator system currently under development.
