### ISSUE TITLE
SCF component have incorrect UAA identify zone URL 

### ISSUE THREAD

**Issue by bstick12** [SUSE/scf#2087]
In the UAA release the uaa.url is 

```
properties.uaa.url: "https://uaa.((DOMAIN)):2793"
```

https://github.com/SUSE/uaa-fissile-release/blob/c9edf8953ae9d3d0b5dcc820cdb3e85c827cefdf/container-host-files/etc/scf/config/role-manifest.yml#L254

In the SCF release the UAA is configured

```
 properties.uaa.url: https://((KUBERNETES_NAMESPACE)).((UAA_HOST)):((UAA_PORT)) 
```
https://github.com/SUSE/scf/blob/f386d3f35f6cee64d37bfdd1f2a81669d5f97b42/container-host-files/etc/scf/config/role-manifest.yml#L2388

This is causing several components not to startup. e.g. gorouter.  The DNS for `uaa.<DOMAIN>` and `scf.uaa.<DOMAIN>` is mapped to the LB service for UAA.

A curl request against `https://scf.uaa.<DOMAIN>:2793` gives a `404` with error `The subdomain does not map to a valid identity zone.`

I can't see a way in the UAA release to add an additional identity zone or a way in the SCF release to not use the `KUBERNETES_NAMESPACE` as part of the UAA url.

**Comment by bstick12** [comment]
Adding an identify-zone `scf` to the running UAA server seems to have gotten me past this particular issue. I don't see this step documented. Is this the correct action to take?

**Comment by jimmykarily** [comment]
For each CF we use a different identity zone. It's creation is happening automatically when you deploy scf but for some reason failed for you. We would need the logs from the `post-deployment-setup` pod to see why this failed.

[The script that creates the identity zone](https://github.com/SUSE/scf/blob/develop/src/scf-release/jobs/uaa-create-user/templates/run.erb#L81)

**Comment by bstick12** [comment]
Thanks - That jobs looks to be failing without creating an actual pod.  I'll dig around and see if I can find why that is.

```
kubectl get pods -n scf  --selector=job-name=post-deployment-setup-1
No resources found.
```

```
kubectl describe job/post-deployment-setup-1 -n scf
Name:           post-deployment-setup-1
Namespace:      scf
Selector:       controller-uid=efcff632-2ecf-11e9-b59a-42010a000100
Labels:         app.kubernetes.io/component=post-deployment-setup-1
                app.kubernetes.io/instance=scf
                app.kubernetes.io/managed-by=Tiller
                app.kubernetes.io/name=cf-opensuse
                app.kubernetes.io/version=2.14.5
                helm.sh/chart=cf-opensuse-2.14.5
                skiff-role-name=post-deployment-setup-1
Annotations:    <none>
Parallelism:    1
Completions:    1
Start Time:     Tue, 12 Feb 2019 14:10:22 +0000
Pods Statuses:  0 Running / 0 Succeeded / 1 Failed
Pod Template:
  Labels:       app.kubernetes.io/component=post-deployment-setup
                app.kubernetes.io/instance=scf
                app.kubernetes.io/managed-by=Tiller
                app.kubernetes.io/name=cf-opensuse
                app.kubernetes.io/version=2.14.5
                controller-uid=efcff632-2ecf-11e9-b59a-42010a000100
                helm.sh/chart=cf-opensuse-2.14.5
                job-name=post-deployment-setup-1
                skiff-role-name=post-deployment-setup
  Annotations:  checksum/config=7b9c38ee83dab6bf577aa6cd08b36ddd7ea7bf3ce73d85bbc3ba30b15b67fd74
  Containers:
   post-deployment-setup:
    Image:      docker.io/eirinicf/scf-post-deployment-setup:9b7ba394ac63a4ff884af16d218424559e7c2ee7
....
Events:                                                     <none>
```

**Comment by satadruroy** [comment]
@bstick12 - does any `post-deployment-setup` pod even show up in `kubectl get po -n scf` list?

**Comment by bstick12** [comment]
@satadruroy It didn't in that deployment but that was after I had manually created the zone. I think I found the root cause of the issue. I create a deployment of the UAA with a incorrect certificate name the first time and didn't release that a helm purge didn't delete and the secret. This was causing subsequent installations to fail. 

Thanks for the assistance
