### ISSUE TITLE
Not able to fork processes as vcap user anymore

### ISSUE THREAD

**Issue by eyenx** [SUSE/scf#2100]
See moby Issue: https://github.com/moby/moby/issues/27444

SUSE SCF images seem to have a nproc limit set  for vcap user (inside the image itself):

```
# tail -5 /etc/security/limits.conf
vcap  soft  nproc  4096
vcap  hard  nproc  4096
*               hard    core            0
```

Because SUSE SCF Pods run processes as vcap user with UID 1000, sometimes it can happen, that too many processes are spawned by UID 1000 on one single Kubernetes node. This brings us  to a race condition where processes inside Pods cannot be started with user vcap anymore and stay in RUNNING state with an unhealthy status "0/1".

Can the limit be raised or can it be customized with HELM Values?

**Comment by jandubois** [comment]
I was looking into user namespace remapping to see if that can help us, but it is not currently supported, and even the planned/proposed feature does not support different mappings per pod:

> Non-goal is to support pod/container level user namespace isolation. There can be images using different users but on the node, pods/containers running with these images will share common user namespace remapping configuration. In other words, all containers on a node share a common user-namespace range.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-usernamespace-remapping.md#non-goals

**Comment by jandubois** [comment]
> See moby Issue: [moby/moby#27444](https://github.com/moby/moby/issues/27444)

Oh, should have followed that link first; even if it was supported the remapping wouldn't help.

**Comment by eyenx** [comment]
Any updates on this? We would really welcome a possibility to change that limits.conf variable with helm values if possible.

**Comment by f0rmiga** [comment]
@eyenx I have an open PR for this issue. I just wanted to confirm if there is any other role other than diego-cell that needs to have this configurable.

**Comment by f0rmiga** [comment]
@eyenx You can use the charts generated by our CI to try it out:
uaa-opensuse -> https://s3.amazonaws.com/cap-release-archives/prs/PR-2155-uaa-opensuse-helm-2.15.2%2Bcf5.5.0.183.gaf596484.tgz
cf-opensuse -> https://s3.amazonaws.com/cap-release-archives/prs/PR-2155-cf-opensuse-helm-2.15.2%2Bcf5.5.0.183.gaf596484.tgz

**Comment by eyenx** [comment]
Hi @f0rmiga

Thanks, will try them out and give feedback! 

Thanks, regards

**Comment by f0rmiga** [comment]
Thanks @eyenx! The PR is still open pending a confirmation if we need that for other roles as well. Let me know when you test them.

Cheers.

**Comment by eyenx** [comment]
Hi @f0rmiga 

Would love to test the charts but:

1. cant pull those images: 

```
secret-generation-1-t2p7x   0/1     ErrImagePull        0          72s
uaa-0                       0/1     ImagePullBackOff    0          71s
docker pull registry.suse.com/cap/uaa-secret-generation:8cad04003d4abda362fed3910424f43b6790ad5c
Error response from daemon: manifest for registry.suse.com/cap/uaa-secret-generation:8cad04003d4abda362fed3910424f43b6790ad5c not found
```

2. This nproc limit should not only been set for diego-cell but for all components of SCF. We were having issues with this when we scaled up  to 3 replicas our SCF MySQL Database & UAA MySQL Database, so not only Diego-Cell (Which by the way are using UID 2000) but also all the other components of SCF are affected by this issue (UID 1000).

**Comment by jimmykarily** [comment]
@eyenx for #1, the images are on dockerhub. Just remove the registry information from your scf-config-values.yaml and let it use the (default) dockerhub. This works:

```
docker pull splatform/uaa-secret-generation:8cad04003d4abda362fed3910424f43b6790ad5c
```

**Comment by eyenx** [comment]
Thanks @jimmykarily that worked.

As expected, the diego-cell-0 is changing the ulimit for the user vcap, but not on all other components like MySQL where we really had the issue a few weeks ago after scaling up to 3 replicas:

Settings:
```
  DIEGO_VCAP_HARD_NPROC: 8192
  DIEGO_VCAP_SOFT_NPROC: 8192
```
diego-cell: 
```
diego-cell/0:~# su - vcap
diego-cell/0:~$ ulimit -u
8192
```
scf-mysql:
```
su mysql/0:/# su - vcap
mysql/0:~$ ulimit -u
4096
```

I would suggest adding the `set_vcap_limits.sh` script to al images and rename the DIEGO_VCAP_HARD/SOFT_NPROC environment variable to something more generic.

How do you see this @f0rmiga ?

**Comment by andreas-kupries** [comment]
The fix is now in our develop work, to be included in the next CAP release.

**Comment by eyenx** [comment]
@andreas-kupries Yes thank you, but is it possible to also implement a env variable to change the nproc limits for other pods, like mysql, gorouter etc.? Our issue was primarly on the mysql poda & not on the diego cells.

**Comment by andreas-kupries** [comment]
@eyenx I believe you missed that @f0rmiga made another commit which changed the var names, and also applied the limit fix to all pods now. The PR merge includes that commit.

Note that as-is the limit change applies to all pods equally.

I am not sure if should read your comment as wanting to apply different limit to different pods ?

**Comment by f0rmiga** [comment]
@eyenx I was waiting for the PR to be reviewed again before commenting back here. As Andreas mentioned, he reviewed again and merged with the changes. I hope it solves the issue.

**Comment by eyenx** [comment]
No sorry I was only on my mobile and didn't saw the additional commit. Thanks very much, this should do it! 

I can now give feedback to our customer.
