### ISSUE TITLE
Flexible Ingress Configuration in Helm Charts

### ISSUE THREAD

**Issue by adrianliechti** [SUSE/scf#2150]
hi scf team,

we super like the direction to use ingress instead of load balancers! thx for that!

since we deploy scf cluster more like "cattle" than "pets", we automatize everything - including dns (external-dns) and tls (cert-manager) etc.
the current approach, to configure tls/secrets manually, is therefore something we would like to workaround.

if you compare your current ingress settings with common charts (on helm/charts/stable), you might notice, that usually, chart creators let add annotations to ingress:

values.yaml:

```
ingress:
  enabled: false
  # annotations:
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  #   kubernetes.io/ingress.class: nginx
  # path: /
  # hosts:
  #   - host1.example.com
  # tls:
  #   - secretName: secretName
  #     hosts:
  #       - host1.example.com
```

could you consider to allow the same flexibility in your ingress?
a quite popular use-case is to use let's encrypt as a TLS provider, or to use a different ingress as traefik or istio

currently we think about something ugly like that:

before scf installation:
- create a dummy application and ingress to generate all certs (uaa, scf etc.)
- export the secret
- use the secret during the installation of scf
- patch the ingress afterwards to allow cert-manager to reissue expired certificates (add some annotations)

thanks for any feedback (or better ideas of workarounds),
adrian

**Comment by HartS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved Ingress configuration](https://trello.com/c/2Y2h5iuG/650-improved-ingress-configuration)

**Comment by HartS** [comment]
Hi @adrianliechti , we have a planning item for this suggestion created internally now. We'll update here if there's any progress; in the meantime I'll see if anyone else has any feedback regarding your proposed workaround.

**Comment by troytop** [comment]
This is an excellent suggestion @adrianliechti and it's similar to some stories on our roadmap. The basic functionality you describe is what we want, but the SCF team need to think hard about how and when to implement this. We have to take into account the work going on upstream to [replace the gorouter with istio et al.](https://www.suse.com/c/istio-a-new-routing-tier-for-cloud-foundry/). Right now the ingress controller hands off to the gorouter, which is sub-optimal.

We'll keep you posted, and keep this issue open.

**Comment by adrianliechti** [comment]
omg! thx 1000 times for working on the ingress template:
- Improved annotations logic (fea8d4080466d33b30ecb508e3c5b2042efacc67) etc.

**Comment by f0rmiga** [comment]
@adrianliechti The feature landed on https://github.com/SUSE/scf/releases/tag/2.16.4.

**Comment by adrianliechti** [comment]
thank you super much for the update!!
we already begun to implement it

we also started testing eirini and are super exited about it. 2.16 seems a super fine release! cheers to you & your whole team

**Comment by f0rmiga** [comment]
@adrianliechti Glad it worked well for you guys! Cheers!
