### ISSUE TITLE
metrics for scf

### ISSUE THREAD

**Issue by ajcs3** [SUSE/scf#2159]
How to fetch the Key Metrics for this cloud foundry components which are stated below:
https://docs.cloudfoundry.org/running/all_metrics.html
In-general in bosh deployment we use firehose to read the metrics exposed by the components. Here we installed prometheus for the cluster monitoring. Is there a way to scrape these cf component metrics using prometheus

**Comment by troytop** [comment]
@nwmac could you provide some insight here about how we do this with stratos-metrics?

**Comment by nwmac** [comment]
@troytop @ajcs3 In Stratos metrics, we use the firehose_exporter - https://github.com/bosh-prometheus/firehose_exporter and Prometheus.

This component attaches to the Cloud Foundry firehose and takes metrics from it and acts as an exporter for Prometheus, feeding those metrics to it. The end result is you get the metrics from Cloud Foundry in Prometheus.

Stratos Metrics provides a Helm chart for deploying the firehose and Prometheus with an nginx instance to provide authentication. You can also look at https://github.com/bosh-prometheus/prometheus-boshrelease which provides a BOSH release for the firehose and Prometheus.

**Comment by ajcs3** [comment]
@nwmac @troytop Thanks for the info.
