### ISSUE TITLE
wait-for-uaa pre-start job - no '--insecure' flag option for curl

### ISSUE THREAD

**Issue by mikkrish** [SUSE/scf#2184]
While deploying scf with self-signed certificate tcp-router container will not start because pre-start script fails while trying to curl https:// uaa url.

Faulty code in file scf/src/scf-release/jobs/wait-for-uaa/templates/pre-start.erb

```
CURL_SKIP="<%= properties.skip_ssl_validation ? '--insecure' : '' %>" 
UAA_ENDPOINT="<%= p('uaa.url') %>"

status "Waiting for UAA ..."
retry 240 30s curl --connect-timeout 5 --fail --header 'Accept: application/json' $UAA_ENDPOINT/info
```

Proposed fix:

```
CURL_SKIP="<%= properties.skip_ssl_validation ? '--insecure' : '' %>" 
UAA_ENDPOINT="<%= p('uaa.url') %>"

status "Waiting for UAA ..."
retry 240 30s curl $CURL_SKIP --connect-timeout 5 --fail --header 'Accept: application/json' $UAA_ENDPOINT/info
```

**Comment by andreas-kupries** [comment]
Thank you for your submission.

Yes, the original code indeed looks buggy.

I have added a ticket for us in our internal systems now.

If I read your pre/post changes correctly the only change made is to the `retry` command, adding the `$CURL_SKIP`, right ? As unified diff it would be:

```
- retry 240 30s curl --connect-timeout 5 --fail --header 'Accept: application/json' $UAA_ENDPOINT/info
+ retry 240 30s curl $CURL_SKIP --connect-timeout 5 --fail --header 'Accept: application/json' $UAA_ENDPOINT/info
```

**Comment by mikkrish** [comment]
@andreas-kupries 
Yes, correct.


This way in file scf/src/scf-release/jobs/wait-for-uaa/spec
if parameter `skip_ssl_validation` is set to `true` , `--insecure` flag will be added to curl, otherwise empty string will be passed as intended.

**Comment by jandubois** [comment]
I would like to understand *why* you want to use a self-signed certificate for UAA and then disable cert validation.

I can only see any benefit to using a self-signed certificate if you would also provide your custom CA cert, so that things can still be validated, but I see that this might currently not be possible, or is at least completely undocumented/supported.

But disabling cert validation on the auth system itself seems like a dangerous proposition. I understand that these are just readiness tests, but I would expect that there are more locations that also would have to disable cert validation for UAA access.

**Comment by jandubois** [comment]
> I see that this might currently not be possible, or is at least completely undocumented/supported.

Actually, I'm completely wrong about this: we always pass the internal CA from UAA to SCF to allow it to validate. When you used your self-signed cert for UAA, did you pass your own CA cert to SCF via the `UAA_CA_CERT` parameter, or did you still specify the internal one from UAA?

If you specified the correct CA cert that was used to sign your UAA cert, then everything should already work without having to skip any validation.

**Comment by mikkrish** [comment]
I meant self-signed certificate that is generated automatically by the built-in secrets generator.

To be clear, I am using official SUSE doc on how to deploy SCF on kubernetes (Amzon EKS).
[Deploy scf](https://www.suse.com/documentation/cloud-application-platform-1/book_cap_guides/data/sec_cap_install-scf-eks.html)

Just as in instruction below:

```
tux > SECRET=$(kubectl get pods --namespace uaa \
-o jsonpath='{.items[?(.metadata.name=="uaa-0")].spec.containers[?(.name=="uaa")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretKeyRef.name}')

tux > CA_CERT="$(kubectl get secret $SECRET --namespace uaa \
-o jsonpath="{.data['internal-ca-cert']}" | base64 --decode -)"

tux > helm install suse/cf \
--name susecf-scf \
--namespace scf \
--values scf-config-values.yaml \
--set "secrets.UAA_CA_CERT=${CA_CERT}"
```

UAA is working, and I can connect to it via `uaac` tool.

(Had to add uaa  zones to scf-config-values.yml manually, as it does not add the automatically generated uaa url with 'scf.' prefix/subdomain. But this is for another issue.)

Problem is when tcp-router container spawns, before service is loaded to monit it runs pre-start check that curls uaa that is self-signed.

**Comment by jandubois** [comment]
Ok, thanks for clarifying that you are using the auto-generated cert. That should definitely work, so either there is something wrong with the documentation, or you have deviated from it somewhere.

The cert should already be installed by the time the wait-for-uaa pre-start script runs.

There are 3 pre-start scripts in the tcp-router container:

```/:~# find /var/vcap/jobs-src/* -name pre-start*
/var/vcap/jobs-src/authorize-internal-ca/templates/pre-start.erb
/var/vcap/jobs-src/tcp_router/templates/pre-start
/var/vcap/jobs-src/wait-for-uaa/templates/pre-start.erb
```

They will run in alphabetical order (shell globbing behavior): https://github.com/cloudfoundry-incubator/fissile/blob/5b678a8c2421cbc1a8cf308a45c2c89bb5a3fbde/scripts/dockerfiles/run.sh#L171-L189

So the authorize-internal-ca pre-start will run first, which will install the UAA CA cert:

https://github.com/cloudfoundry-incubator/fissile/blob/5b678a8c2421cbc1a8cf308a45c2c89bb5a3fbde/scripts/dockerfiles/run.sh#L171-L189

The `uaa.ca_cert` property is set to the `UAA_CA_CERT` config variable:

https://github.com/SUSE/scf/blob/267eeb187e9d18dd170f168137f019ae57c8762e/container-host-files/etc/scf/config/role-manifest.yml#L2752

So the only explanation I have is that somehow you did not end up with the correct value in `CA_CERT`. Can you double-check that this variable includes a cert and not just an empty string?

**Comment by jandubois** [comment]
> Maybe there is a problem with kubernetes StatefulSets, but im pretty sure I did it right as described here:
> [Deleting and Rebuilding a Deployment](https://www.suse.com/documentation/cloud-application-platform-1/book_cap_guides/data/sec_cap_rebuild_depl.html)

Just took a look at that page and noticed that the example only deletes UAA. Did you run the corresponding commands to delete the `scf` namespace as well?
