### ISSUE TITLE
Add support for using an external database

### ISSUE THREAD

**Issue by troytop** [SUSE/scf#2349]
Some operators may wish to use a CSP-provided data service, or an existing HA database server/service for the MySQL database backing UAA and the CC. Expose options in the Helm values.yaml to use these services.

**Comment by mook-as** [comment]
Is this a common enough case to need a knob, or is doing the override via the [arbitrary bosh property overrides](https://github.com/SUSE/scf/#customize-the-application-domain) (and scaling the internal mysqls to 0) enough? We'd need to test that it works, of course.

**Comment by jandubois** [comment]
> scaling the internal mysqls to 0

That is no longer possible. You would have to add a `default_feature: mysql` to the instance group and then you can `--set enable.mysql=false`. So you still need *some* change somewhere; it will not work as-is with CAP 1.4.

**Comment by troytop** [comment]
It's OK to have this as a 2.0 feature. It is not needed urgently by anyone, but it has been requested by a CSP who would rather have the cluster backed by their MySQL service.

**Comment by gaktive** [comment]
To be looked at post-1.5 (scf 2.18.0+)

**Comment by f0rmiga** [comment]
This is possible with KubeCF, which is the base for the already-released CAP 2.0.
