### ISSUE TITLE
Include cc_deployment_updater (to support Rolling App Deployment)

### ISSUE THREAD

**Issue by marcelhintermann** [SUSE/scf#2460]
For Rolling App Deployment (zero downtime deployment) cc_deployment updater is needed.
The feature is still marked as beta in CLI but i would love to give it a try.

https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html

The prerequisites are:
-  :heavy_check_mark: capi-release v0.168.0
- :x: cc_deployment_updater 

As far as i know, the only thing needed is support for the cc_deployment_updater.

**Comment by jandubois** [comment]
Thank you for your feedback. Adding the `cc_deployment_updater` is already in our backlog, but I have no idea when the work will be scheduled.

[CAP-173]
