### ISSUE TITLE
Vagrant up had an error: mount.nfs: access denied by server while mounting 192.168.47.1:/root/workspace/xiujuan/scf/.fissile/.bosh

### ISSUE THREAD

**Issue by xiujuan95** [SUSE/scf#2587]
I fellow the guide of deploying SCF on Vagrant to deploy SCF in my environment. But I met a problem when I ran the command (vagrant up) to set up a virtualbox. Details about the error are shown below:

Vagrant version: Vagrant 2.0.1

![image](https://user-images.githubusercontent.com/52686173/61513266-23a96680-aa2f-11e9-84d7-55af08cacf3f.png)

In order to solve it, I find a method by Google searching. But I can't check it. Please refer to https://github.com/hashicorp/vagrant/issues/9918 about this method.
I think maybe you can try it. If there has any ideas, please let me know. Thanks

**Comment by mook-as** [comment]
Do you have multiple network interfaces on your host (what appears to be `cf-lite-dev`)? I believe @jandubois mentioned something about Vagrant finding the wrong interface (and putting the wrong thing in `/etc/exports`) in that case.

If that is your issue, it appears that the relevant tickets are https://github.com/hashicorp/vagrant/issues/5424 / https://github.com/hashicorp/vagrant/issues/8704 (and we can't fix it from the SCF side).

**Comment by xiujuan95** [comment]
Thank you for your ideas. I have fixed it by switching the working directory. Before, I ran "vagrant up" in scf folder. I exit it to run the command and everything is normal. I will close this issue.

**Comment by jandubois** [comment]
> I have fixed it by switching the working directory.

I'm amazed that this works. Vagrant normally starts a VM based on the `Vagrantfile` in the current directory. If you are switching to a different directory, you are no longer starting the SCF development VM, but some other VM that is described by the `Vagrantfile` in that directory...

**Comment by xiujuan95** [comment]
@jandubois Maybe I didn't express my idea clearly. You are right. Before, I tried to set up a VM in scf folder. Although there has Vagrantfile file in scf folder, the previous problem occured. Actually, I don't know why it happened. If you have any ideas, please let me know. Thanks! But, now, I exit scf folder, run "vagrant init hashicorp/precise64" command to create another Vagrantfile file and do the same thing to set up a VM in this directory, everything is OK.

**Comment by xiujuan95** [comment]
Because the network IP address conflict in our environment. Now, I have fixed this problem. So I will close this issue.

**Comment by micktg** [comment]
If you are coming here because you are using macOS Catalina, this might help: https://github.com/hashicorp/vagrant/issues/10961

**Comment by ilithium** [comment]
So I just resolved this on my Catalina install. After trying all kinds of variations, I renamed my project folder to remove the space in its name and this seems to have fixed the issue.

So it looks like whatever Vagrant is doing to generate /etc/exports doesn't account for " " in the path.
