### ISSUE TITLE
Where does scf-3.0.0-8f7a71d1.tgz come from?

### ISSUE THREAD

**Issue by drnic** [SUSE/scf#2756]
Sorry for being confused.

In the hands-on labs at cfsummit we installed a helm chart `scf-3.0.0-8f7a71d1.tgz` from https://github.com/cloudfoundry/summit-hands-on-labs/tree/master/the-hague-2019/quarks-cf-on-k8s#installing-scf

But in this project's releases seem different:

* highest released version is 2.17.1
* highest tag is 2.18.0-rc4
* release artefact is different in name prefix (scf- vs scf-sle-), name suffix (tgz vs zip), and contents (single helm chart vs several charts)

Where does scf-3.0.0-8f7a71d1.tgz come from?

**Comment by jandubois** [comment]
It is built from the v3 branch: https://github.com/SUSE/scf/tree/v3-develop

It is *very* different from the other branches in this repo...

**Comment by drnic** [comment]
Thanks for link to alternate branch.

I'll create a new issue for adding v3 releases to github release.
