### ISSUE TITLE
Make PodSecurityPolicies compatible with K8s 1.16

### ISSUE THREAD

**Issue by akshaymankar** [SUSE/scf#2763]
As announced [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/), deprecated APIs are being removed from K8s 1.16, which is scheduled to be released tomorrow, 18 Sep 2019 as specified [here](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.16#tldr).

The PodSecurityPolicies in SCF use `extensions/v1beta1`, they should now use `policy/v1beta1`

related to https://github.com/cloudfoundry-incubator/fissile/issues/514

**Comment by gaktive** [comment]
Thanks for letting us know! We've added a story in our backlog to work on this.

**Comment by loewenstein** [comment]
Any progress on this? @viovanov I guess we should have an issue for this in https://github.com/cloudfoundry-incubator/cf-operator

**Comment by f0rmiga** [comment]
This was fixed in https://github.com/cloudfoundry-incubator/fissile/issues/514, and KubeCF is out-of-scope for this repository (but it does support the latest k8s version - 1.18).
