### ISSUE TITLE
Spike: BOSH-compatible hostname aliases

### ISSUE THREAD

**Issue by viovanov** [SUSE/scf#2780]
A lot of the ops files in SCF are concerned with changing hostnames (in properties as well as certificates).
Everything would be simpler if we could re-use the hostnames used by the BOSH releases.

**Comment by kramerul** [comment]
We are currently working on a PR for the cf-operator.
This PR will use the configuration from the BOSH-dns-addon to do the replacement of job properties (uaa.service.cf.internal -> uaa.<namespace>.svc.cluster.local). 
Additionally the first part from the domain is used as service name.
We are quite new to this project and we would like to learn more about it.

**Comment by kramerul** [comment]
We provided a PR for the cf-operator. To complete this issue, the propose the following steps
* Merge PR
* Remove DNS replacements from OPS files. Add nats and eirini to bosh dns.
* Remove rewrites to old headless service names from cf-operator
