### ISSUE TITLE
Expose SCF v3 publicly

### ISSUE THREAD

**Issue by viovanov** [SUSE/scf#2811]
As an SCF v3 adminstrator, I'd like to expose my SCF v3 to the public, using one of:

- load balancer
- ingress controller
- an `external_ip`

I need to understand how to plan for this, because of how DNS and public IP address mechanisms work.
I'd like to be able follow docs for this.

**Comment by f0rmiga** [comment]
@viovanov We already can access SCF v3 publicly via ingress controller. We have https://github.com/SUSE/scf/blob/v3-develop/deploy/helm/scf/templates/ingress.yaml. Can I mark this issue as done?

**Comment by f0rmiga** [comment]
After talking to @viovanov about LB and external IP, we agreed that we will also have a Helm template for another service for the router pod.

**Comment by f0rmiga** [comment]
Done on https://github.com/SUSE/scf/pull/2849.
