### ISSUE TITLE
Make ingress objects usable with cert-manager

### ISSUE THREAD

**Issue by akshaymankar** [SUSE/scf#2856]
**Is your feature request related to a problem? Please describe.**

We are trying to deploy SCF with helm chart on GKE. We decided to use cert-manager to generate certificates for go-router and uaa. 
If we try to put the annotation `certmanager.k8s.io/issuer` on the ingress, the secret gets overwritten on `helm upgrade`. 
If we put the TLS creds in `ingres.tls...` helm values, then certificate rotation has to be done manually.

**Describe the solution you'd like**

Create the `ingress-tls` secret only when certificates are provided, otherwise let cert-manager or users create the secret.

**What is the impact?**

Using cert-manager would be easier, might help in adoption a little :)

**How to measure it?**

Not sure.

/cc @alex-slynko @julz

**Comment by satadruroy** [comment]
Hi, I'm not sure I entirely follow this. If you are deploying with an Ingress Controller all the requests would get funnelled through the IC on to go-router and so on so the certs need to be set-up just on the Ingress Controller with the various hostnames the Ingress objects expose for UAA and SCF backends.

For a sample e2e installation with cert-manager integration of CAP with Ingress Controller on GKE please see: 

https://github.com/SUSE/cap-terraform/tree/e2e-cap-deploy

**Comment by akshaymankar** [comment]
Hi @satadruroy,

I was under an impression that helm would overwrite the secret on upgrades. But I found [this comment](https://github.com/helm/helm/issues/5430#issuecomment-472451791) on helm which explains why my assumption was wrong. I guess I can close this issue.

Thanks,
Akshay && @gdankov

**Comment by alex-slynko** [comment]
This will be no longer the case with Helm 3
https://v3.helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

**Comment by akshaymankar** [comment]
The documentation talks about only rollbacks. If my understanding of 3-way merges is correct, on upgrades, it should still keep the old state.

**Comment by alex-slynko** [comment]
Reopened because it might be affected by using `helm template`.

**Comment by f0rmiga** [comment]
Closing as we don't support `helm template`. Please, reopen and ping me if I'm missing something.
