### ISSUE TITLE
Gitlab CI helm charts into s3 bucket

### ISSUE THREAD

**Issue by drnic** [SUSE/scf#2869]
From https://cloudfoundry.slack.com/archives/C1BQKKNP4/p1570095189131600

@f0rmiga could the new gitlab pipelines put the successful helm charts into the `scf-v3` bucket please?

**Comment by drnic** [comment]
Maybe this isn't an issue - maybe no new code is on `v3-develop` into which a new release would have been cut? :)

**Comment by f0rmiga** [comment]
The Gitlab manifest was bugous. We are back to business: https://gitlab.com/susecf/scf/-/jobs/314285646.
