### ISSUE TITLE
scf-router-v1-0 > bpm-pre-start-gorouter failing - DNS is not up

### ISSUE THREAD

**Issue by drnic** [SUSE/scf#2880]
```
scf-router-v1-0 bpm-pre-start-gorouter + /var/vcap/jobs/gorouter/bin/bpm-pre-start
scf-router-v1-0 bpm-pre-start-gorouter Host scf-uaa not found: 3(NXDOMAIN)
scf-router-v1-0 bpm-pre-start-gorouter DNS is not up
```

Any protips or ideas what might cause this? Is it a CF-related DNS issue, a Kube DNS issue?

The scf-uaa-v1-0 job looks to be running:

```
scf-uaa-v1-0                     7/7     Running                 0          5m9s
```

**Comment by mook-as** [comment]
In my experience, the router will try a bit, and get into CrashLoopBackoff, before UAA is up. Once that happens it takes a bit for Kube to try starting the router again (at which point it will resolve `scf-uaa`, and things can proceed).  Until `scf-uaa-v1-0` (or whatever) is ready, though, we'll get a `NXDOMAIN`.

It looks like your UAA is ready (7/7 containers look fine); the length of time they've been ready, though, isn't the same as the amount of time the pod has been created (the `5m9s` part).

**Comment by drnic** [comment]
thanks @mook-as
