### ISSUE TITLE
The helm charts don't work with helm 2.15

### ISSUE THREAD

**Issue by akshaymankar** [SUSE/scf#3043]
**Describe the bug**
The `apiVersion` in `Chart.yaml` is wrong. It is supposed to be `v1`, but it is `2.18.0+cf9.5.0.0.ga2697c75` in the latest release.

**To Reproduce**
Use helm 2.15 and try to install the charts.

**Expected behavior**
Charts get installed.

**Logs**
```
Release "uaa" does not exist. Installing it now.
Error: apiVersion '2.18.0+cf9.5.0.0.ga2697c75' is not valid. The value must be "v1"
```

**Environment**
 - SCF version: 2.18
 - Modules enabled: N/A
 - Other specifics: N/A

**Comment by mook-as** [comment]
Hi! This should be fixed in #3007; we haven't had a release since though.
