### ISSUE TITLE
Failing to download vagrant box base image with 403 error

### ISSUE THREAD

**Issue by m-lukas** [SUSE/scf#3073]
**Describe the bug**
I worked on changing the network of my SCF vagrant box to a "public_network" but had some issues with the rebooting of the VM and therefore wanted to start from scratch again. In order to do this, I destroyed the box and subsequently removed the box to delete all files. Now I'm trying to start it up again by using `vagrant up --provider virtualbox` but running into a new issue because it's failing to download the vagrant box base image (`https://cf-opensusefs2.s3.amazonaws.com/vagrant/scf-virtualbox-v2.0.17.box`). The error it produces is a http-error 403: Forbidden. If I'm trying to open the url in my browser, the same error code occurs.

**To Reproduce**
* `vagrant destroy`
* `vagrant box remove https://cf-opensusefs2.s3.amazonaws.com/vagrant/scf-virtualbox-v2.0.17.box`
* `vagrant up --provider virtualbox`
or
* vagrant box add https://cf-opensusefs2.s3.amazonaws.com/vagrant/scf-virtualbox-v2.0.17.box --name https://cf-opensusefs2.s3.amazonaws.com/vagrant/scf-virtualbox-v2.0.17.box

**Expected behavior**
Vagrant should be able to download the base image and provision a new VM to which I can connect using SSH.

**Logs**
```shell
vagrant up --provider virtualbox 
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'https://cf-opensusefs2.s3.amazonaws.com/vagrant/scf-virtualbox-v2.0.17.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: It looks like you attempted to add a box with a URL for the name...
==> default: Instead, use box_url instead of box for box URLs.
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'https://cf-opensusefs2.s3.amazonaws.com/vagrant/scf-virtualbox-v2.0.17.box' (v0) for provider: virtualbox
    default: Downloading: https://cf-opensusefs2.s3.amazonaws.com/vagrant/scf-virtualbox-v2.0.17.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden
```
**Environment**
 - SCF version: **v2.18.0 (latest)**
 - Modules enabled: **yes**
 - Other specifics: **-**

**Comment by jandubois** [comment]
Sorry about this! It looks like somebody made the bucket private in preparation for deletion because they (wrongly) assumed that it wasn't used anymore. I've asked to make it public again.

**Comment by m-lukas** [comment]
Thank you very much! I'm currently working on a project for my university and try to setup a small local cluster with CF to showcase it :)

**Comment by jimmykarily** [comment]
Made the file public again and downloading works. Thank you @m-lukas for reporting this.
