### ISSUE TITLE
git submodule problem

### ISSUE THREAD

**Issue by zreigz** [SUSE/scf#970]
There is some problem with repositories from src/
After 

```
git submodule sync --recursive
git submodule update --init  --recursive

```
some repositories are empty. For instance src/diego-release and I have the following error:

```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:suse/testbrain.git' into submodule path '/home/vagrant/scf/src/hcf-release/src/github.com/suse/testbrain' failed
Failed to clone 'src/hcf-release/src/github.com/suse/testbrain' a second time, aborting

```

**Comment by viovanov** [comment]
@zreigz we need to make that submodule reference an http remote
can you make the change locally and verify it fixes your problem?
remote should be https://github.com/SUSE/testbrain.git

**Comment by zreigz** [comment]
I've already fixed it in PR https://github.com/SUSE/scf/pull/971 and it seems to work

**Comment by zreigz** [comment]
I can confirm it works now

**Comment by viovanov** [comment]
thanks @zreigz
