### ISSUE TITLE
`make kube` fails because of missing env variables

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/scf#992]
When I try to run `make kube` as per the documentation [here](https://github.com/SUSE/scf#deploying)
I get errors like:

```
vagrant@vagrant-kube:~/scf> make kube
/home/vagrant/scf/make/uaa-kube
make[1]: Entering directory '/home/vagrant/scf/src/uaa-fissile-release'
/home/vagrant/scf/src/uaa-fissile-release/make/kube-configs
Loading defaults from env files
Secret 'MYSQL_ADMIN_PASSWORD' has no value
Makefile:16: recipe for target 'kube-configs' failed
make[1]: *** [kube-configs] Error 1
make[1]: Leaving directory '/home/vagrant/scf/src/uaa-fissile-release'
Makefile:206: recipe for target 'uaa-kube' failed
make: *** [uaa-kube] Error 2
```
I think the problem lies in this line:

https://github.com/SUSE/uaa-fissile-release/blob/001f793a0890d0a240eb3f1447eefcef81895f6a/make/kube-configs#L15

where the files we use do not include this one:
https://github.com/SUSE/scf/blob/develop/bin/settings/settings.env

changing the above line to `    --defaults-file="$(echo env/*.env | tr ' ' ','),../../bin/settings/settings.env" \
` makes it work but I'm not sure this is the right way to do it.

**Comment by jimmykarily** [comment]
After changing the line as described and running `make run` I get this output from `pod-status` for the uaa pods:

```
uaa          mysql-0                               0/1    secrets  "secret-1"  not  found  0  2m
uaa          uaa-2183978632-wd0l3                  0/1    secrets  "secret-1"  not  found  0  2m
```

**Comment by andreas-kupries** [comment]
Ok. Your system seems to be in a very inconsistent state, with pieces from differences commits.
Notably
- You are using a version of `fissile` which generates a `secrets-1.yml`.
- The scripts for SCF's `make run` however are a version which does not know about this file.

Conclusion: You are very likely using a new `fissile` version in an older checkout of `scf`.
Given your slow internet the fastest solution to that likely is to
- Remove the `output` directory in your `scf` checkout, and then
- run `bin/dev/install_tools.sh` manually.

This will install a `fissile` which matches your `scf` checkout.

Regarding the initial problem with `MYSQL_ADMIN_PASSWORD`, that also points to inconsistent state.
When the `fissile` supporting K8s secrets was made the same issue was seen and `uaa-fissile-release` got an update to fix that, namely https://github.com/SUSE/uaa-fissile-release/commit/cc5be52a51e82885140dddeb9bbb955de349c29c

This seems to be missing in your checkout. And is another indicator that you are using a pre-secret SCF/UFR checkout together with a post-secret `fissile`.

HTH.

**Comment by jimmykarily** [comment]
I did a 

```
git reset --hard upstream/develop
git submodule update --recursive
```

and rebuilt the vagrant box. `make kube` now works without a problem. Thanks. Closing this.

**Comment by andreas-kupries** [comment]
You are welcome, and I am glad to hear that it worked out.
